#! /bin/bash

#  prplMesh Wi-Fi Multi-AP
#
#  Copyright (c) 2018, prpl Foundation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Make sure we are root
test $(id -u) = 0 || exec sudo "$0" "$@"

al_entity_exec="$1"; shift
test -x "${al_entity_exec}" || {
  echo "$0: $al_entity_exec not executable" 1>&2
  exit 1
}

stop_interfaces() {
  # If there is a background job, kill it
  kill %1 2>/dev/null || true
  wait %1 2>/dev/null # Suppress "Terminated" output
  for num in 0 1 2 3; do
    ip link delete aletest$num
  done
}

trap stop_interfaces EXIT

interfaces=""
for num in 0 1 2 3; do
  ip link add aletest$num type veth peer name aletestpeer$num
  ip link set dev aletest$num up address 00:ee:ff:33:44:${num}0
  ip link set dev aletestpeer$num up address 00:ee:ff:33:44:${num}1
  interfaces="${interfaces}${interfaces:+,}aletest${num}:simulated:aletest${num}.sim"
done

# Generate 8MB core files
ulimit -c 8000

"$al_entity_exec" -m 02:ee:ff:33:44:00 -i "$interfaces" -r aletest2 -v -v &

"$@" || exit $?

# Test that background job is still running.
jobs %1 >/dev/null 2>&1 || exit 1

